edition: 1.0.0

name: aliyun-fs-container
access: default
services:
  GoGinCustomContainer:
    component: fc
    props:
      region: cn-hongkong
      service:
        name: aliyun-fs-container
      function:
        name: aliyun-fs-container
        runtime: custom-container
        timeout: 60
        memorySize: 1024
        caPort: 9000
        customContainerConfig:
          image: registry-intl.cn-hongkong.aliyuncs.com/istores-app/aliyun-fs-container:v0.1
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
